"""novo campo updated_at na tabela user

Revision ID: 13ec57e0c3d1
Revises: 07a1c998f064
Create Date: 2025-08-04 10:42:01.112367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ec57e0c3d1'
down_revision: Union[str, Sequence[str], None] = '07a1c998f064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
